service: ServerlessRestfulApi

provider:
  name: aws
  runtime: dotnetcore2.1
  region: eu-west-1
  profile: personal

functions: ${file(functions.yml)}

plugins:
  - serverless-iam-roles-per-function

package: 
  artifact: src\bin\release\netcoreapp2.1\ServerlessRestfulApi.zip