 version: 2.1

 orbs:
  node: circleci/node@2.0.2
  win: circleci/windows@2.2.0

 jobs:
   prepare:
     executor: node/default
     steps:
       - checkout
       - run: yarn install
       
   build:
     executor: win/default    
     steps:
       - checkout
       - run: yarn build
   
   deploy:
     executor: node/default
     steps:
       - checkout
       - run: yarn serverless deploy 

 workflows:
   main:
     jobs:
       - prepare
       - build:
          requires:
            - prepare
       - deploy:
          requires:
            - build