 version: 2.1

 orbs:
  nodejs: circleci/node@2.0.2

 jobs:
   prepare:
     executor: nodejs
     steps:
       - checkout
       - run: yarn install
       
   build:
     executor: nodejs    
     steps:
       - checkout
       - run: yarn build
   
   deploy:
     executor: nodejs
     steps:
       - checkout
       - run: yarn serverless deploy 

 workflows:
   main:
     jobs:
       - prepare
       - build:
          requires:
            - prepare
       - deploy:
          requires:
            - build